module.exports = {
    plugins: [require('daisyui')],
    daisyui: {
        themes: [
            {
                mytheme: {
                    "primary": "#9df2d8",
                    "secondary": "#e814ac",
                    "accent": "#c207ed",
                    "neutral": "#221B27",
                    "base-100": "#262740",
                    "info": "#5B92CD",
                    "success": "#16835D",
                    "warning": "#996C0B",
                    "error": "#EC534B",
                },
            },
            'system',
            'light',
            'dark',
            'cupcake',
            'bumblebee',
            'emerald',
            'corporate',
            'synthwave',
            'retro',
            'cyberpunk',
            'valentine',
            'halloween',
            'garden',
            'forest',
            'aqua',
            'lofi',
            'pastel',
            'fantasy',
            'wireframe',
            'black',
            'luxury',
            'dracula',
            'cmyk',
            'autumn',
            'business',
            'acid',
            'lemonade',
            'night',
            'coffee',
            'winter'
        ],
    },
};